### ISSUE TITLE
Certificate does not reconcile on CA changes

### ISSUE THREAD

**Issue by davidhadas** [knative-sandbox/control-protocol#274]
Seems like when a new CA is created, the namespace certificates are not reconciled. 

From code:
```
func parseAndValidateSecret(secret *corev1.Secret, shouldContainCaCert bool) (*x509.Certificate, *rsa.PrivateKey, error) {
        ...
        if shouldContainCaCert {
		if _, ok := secret.Data[certificates.SecretCaCertKey]; !ok {
			return nil, nil, fmt.Errorf("missing ca cert bytes")
		}
	}
         ...
}
```

There is no validation that the secret's ca-public-cert equals the current defacto ca-public-cert in the ca secret.
The code only checks if the ca-public-cert is missing from the secret, not if it is valid.

**Comment by davidhadas** [comment]
@evankanderson, @ReToCode, @nak3
FYI

**Comment by evankanderson** [comment]
I'm guessing if you leave things for about 12 hours, they'll all be updated.

If so, this means that the certificates don't have a watch on the CA secret.  We should think about how we want a CA rotation to roll out -- I'm not sure that a thundering herd of new Certificates will be the best experience; we may also need to think about clients knowing both the old and new CA during the changeover.

If the certs **never** update, then that probably means that our update logic doesn't actually check that the cert is properly signed against the expected CA, which is probably part of the reconciliation logic.

**Comment by davidhadas** [comment]
> I'm guessing if you leave things for about 12 hours, they'll all be updated.

14 hours later - the problem was not fixed.
WHere do we have a 12-hour timer?


> If so, this means that the certificates don't have a watch on the CA secret. We should think about how we want a CA rotation to roll out -- I'm not sure that a thundering herd of new Certificates will be the best experience; we may also need to think about clients knowing both the old and new CA during the changeover.
> 
> If the certs **never** update, then that probably means that our update logic doesn't actually check that the cert is properly signed against the expected CA, which is probably part of the reconciliation logic.

My understanding is that we do not check that the public ca cert is not checked. 
@evankanderson  - you raised "yet another issue" - seems like we also never check if the secret is properly signed.
Here is how we validate the certificate right now:
```golang
// ValidateCert checks the expiration of the certificate
func ValidateCert(cert *x509.Certificate, rotationThreshold time.Duration) error {
	if !cert.NotAfter.After(time.Now().Add(rotationThreshold)) {
		return fmt.Errorf("certificate is going to expire %v", cert.NotAfter)
	}
	return nil
}
``` 

We recently added a follow-up sans check. 
We need to either ensure we create a complete check of the certificate (or maybe we can recreate a new certificate based on the keys used by the current certificate and check that the resulting certificate match byte-wise.. ???)

Are we concerned about an attacker creating his own certificate with his own private key? If so,  we should always create a new certificate if anyone (which is not us) changed the Secret...

**Comment by evankanderson** [comment]
I'm traveling this week, but I'm not sure generating new certificates will protect against an attacker that can mint their own certificates.

**Comment by davidhadas** [comment]
I just verified this again and found the code changes needed.

we need to replace the signature of the parseAndValidateSecret function
```
cert, _, err := parseAndValidateSecret(secret, true, sans...)
```
To include caCert and verify that the caCert is the same as in the secret. If not, update the secret.
```
cert, _, err := parseAndValidateSecret(secret, caCert, sans...)
```
